=== SymbianSource/oss.FCL.sftools.dev.ui/carbideui/com.nokia.tools.platform.core/src/dtds/idmapping.dtd
<?xml version='1.0' encoding='us-ascii'?>

<!--THIS FILE SHOULD NOT BE MODIFIED OR DELETED-->

<!--DTD for idmapping.xml file-->


<!ELEMENT idMappings (skinIdMappings?, layoutMappings?)+ >
<!ATTLIST idMappings>

<!ELEMENT skinIdMappings (skinEntity+)>

<!ELEMENT skinEntity (layout+)>
<!ATTLIST skinEntity
            id          	CDATA  		#IMPLIED	
>

<!ELEMENT layout EMPTY>
<!ATTLIST layout
            name          	CDATA  		#IMPLIED
            display  		CDATA		#IMPLIED
>


<!ELEMENT layoutMappings (layoutEntity+)>

<!ELEMENT layoutEntity (skin+)>
<!ATTLIST layoutEntity
            name          	CDATA  		#IMPLIED	
            display			CDATA 	 	#IMPLIED
>

<!ELEMENT skin EMPTY>
<!ATTLIST skin
            id          	CDATA  		#IMPLIED
>

=== SymbianSource/oss.FCL.sftools.dev.ui/carbideui/Symbian3/config/IdMappings.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE idMappings SYSTEM "idmapping.dtd">
<idMappings>
  <layoutMappings>
    <!-- Screen -->
    <layoutEntity display="portrait,landscape"
                  name="screen_g1@V:0">
      <skin id="qsn_bg_screen" />
      <skin id="qsn_bg_screen_idle" />
      <skin id="qgn_home_contactname_bg" />
      <skin id="qgn_home_add" />
      <skin id="qgn_home_edit_mode" />
      <skin id="qgn_home_edit_bg_widget" />
      <skin id="qgn_home_photo_mask" />
      <skin id="qgn_indi_home_profile_silent" />
      <skin id="qgn_indi_home_profile_timed" />
      <skin id="qgn_indi_sctrl_sk_mask_middle_prt" />
      <skin id="qgn_indi_ai_eplg_unread" />
      <skin id="qgn_indi_ai_eplg_default" />
      <skin id="qgn_indi_ai_eplg_read" />
      <skin id="qgn_home_refreshing_1" />
      <skin id="qgn_home_refreshing_2" />
      <skin id="qgn_home_refreshing_3" />
      <skin id="qgn_home_refreshing_4" />
      <skin id="qgn_home_refreshing_fails" />
      <skin id="qgn_home_widget_offline" />
      <skin id="qgn_prop_home_add_friend" />
      <skin id="qgn_prop_home_default_friend" />
      <skin id="qsn_home_clock_analogue_pointer_hour" />
      <skin id="qsn_home_clock_analogue_pointer_minute" />
      <skin id="qsn_home_clock_analogue_face" />
      <skin id="qgn_graf_music_home_anim_download00" />
      <skin id="qgn_graf_music_home_anim_download01" />
      <skin id="qgn_graf_music_home_anim_download02" />
      <skin id="qgn_graf_music_home_anim_download03" />
      <skin id="qgn_graf_music_home_anim_download04" />
      <skin id="qgn_graf_music_home_anim_download05" />
      <skin id="qgn_graf_music_home_anim_download06" />
      <skin id="qgn_graf_music_home_anim_download07" />
      <!--<skin id="qgn_home_page_63" />-->
      <skin id="background" />
      <skin id="SoundRingingTone" />
      <skin id="SoundMessageAlert" />
      <skin id="qgn_indi_input_close" />
      <skin id="qgn_graf_adapt_search_bg" />
      <skin id="qgn_graf_fep_bg_colour" />
      <skin id="qgn_graf_fep_input_bg" />
      <skin id="qgn_graf_fep_candi_list_pressed" />
      <skin id="qgn_graf_fep_candi_list_pri" />
      <skin id="qgn_graf_fep_candi_list_sec" />
      <skin id="qgn_graf_fep_candi_list_sel" />      
      <skin id="qgn_prop_set_service" />
      <skin id="qgn_prop_set_voip_advanced" />
      <skin id="qgn_menu_am_widget" />
      <skin id="qgn_prop_video_no_right" />
      <skin id="qgn_prop_video_valid_right" />
      <skin id="qgn_prop_mg_gamsnapps" />
      <skin id="qgn_prop_folder_vc_general" />
      <skin id="qgn_prop_folder_vc_message" />
      <skin id="qgn_prop_folder_vc_organiser" />
      <skin id="qgn_prop_folder_vc_profiles" />
      <skin id="qgn_prop_folder_vc_tools" />
      <skin id="qgn_prop_set_apps_mp" />
      <skin id="qgn_prop_mp_folder_recent_played" />
      <skin id="qgn_menu_imageprint" />
      <skin id="Screensaver" />
      <skin id="qsn_fr_keypad_button2_normal" />
      <skin id="qsn_fr_keypad_button2_inactive" />
      <skin id="qsn_fr_keypad_button2_pressed" />
      <skin id="qsn_fr_separator_h_l_shdwin" />
      <skin id="qsn_fr_separator_v_t_shdwin" />
      <skin id="qgn_indi_browser_tb_bm" />
      <skin id="LAY_AH%qgn_prop_unsupported_file" />
      <skin id="qgn_indi_sct_close" />
      <skin id="qgn_indi_itut_close" />
      <skin id="qgn_indi_button_decrease" />
      <skin id="qgn_indi_button_decrease_pressed" />
      <skin id="qgn_indi_button_increase" />
      <skin id="qgn_indi_button_increase_pressed" />
      <skin id="qsn_fr_separator_h_l_shdwnone" />
      <skin id="qsn_fr_separator_h_l_shdwout" />
      <skin id="qsn_fr_separator_h_m_shdwin" />
      <skin id="qsn_fr_separator_h_m_shdwnone" />
      <skin id="qsn_fr_separator_h_m_shdwout" />
      <skin id="qsn_fr_separator_h_r_shdwin" />
      <skin id="qsn_fr_separator_h_r_shdwnone" />
      <skin id="qsn_fr_separator_h_r_shdwout" />
      <skin id="qsn_fr_separator_v_b_shdwin" />
      <skin id="qsn_fr_separator_v_b_shdwnone" />
      <skin id="qsn_fr_separator_v_b_shdwout" />
      <skin id="qsn_fr_separator_v_m_shdwin" />
      <skin id="qsn_fr_separator_v_m_shdwnone" />
      <skin id="qsn_fr_separator_v_m_shdwout" />
      <skin id="qsn_fr_separator_v_t_shdwnone" />
      <skin id="qsn_fr_separator_v_t_shdwout" />
      <!--  Music Player 3 Icons  -->
      <skin id="qgn_graf_blid_dirring_mask" />
      <skin id="qsn_cp_scroll_horizontal_handle_top" />
      <skin id="qsn_cp_scroll_horizontal_handle_top_pressed" />
      <skin id="qsn_cp_scroll_horizontal_handle_middle_pressed" />
      <skin id="qsn_cp_scroll_horizontal_handle_bottom_pressed" />
      <skin id="qsn_cp_scroll_horizontal_bg_top_pressed" />
      <skin id="qsn_cp_scroll_horizontal_bg_middle_pressed" />
      <skin id="qsn_cp_scroll_horizontal_bg_bottom_pressed" />
      <skin id="qsn_cp_scroll_horizontal_handle_middle" />
      <skin id="qsn_cp_scroll_horizontal_handle_bottom" />
      <skin id="qgn_graf_rkm_all" />
      <skin id="qgn_graf_rkm_all_dim" />
      <skin id="qgn_graf_rkm_pause" />
      <skin id="qgn_graf_rkm_pause_next" />
      <skin id="qgn_graf_rkm_pause_prev" />
      <skin id="qgn_graf_rkm_play" />
      <skin id="qgn_graf_rkm_play_next" />
      <skin id="qgn_graf_rkm_play_prev" />
      <!-- 
                        <skin id="qgn_graf_rkm_play_prev_dim" />
                        <skin id="qgn_graf_rkm_play_next_dim" />
                        <skin id="qgn_graf_rkm_pause_prev_dim" />
                        <skin id="qgn_graf_rkm_pause_next_dim" />
                        <skin id="qgn_graf_rkm_stop_next_dim" />
                        <skin id="qgn_graf_rkm_stop_prev_dim" />
                        -->
      <skin id="qgn_graf_rkm_stop_prev" />
      <skin id="qgn_graf_rkm_stop" />
      <skin id="qgn_graf_rkm_stop_next" />
      <skin id="qgn_graf_mup_podcast_art" />
      <skin id="qgn_graf_mup_npv_prbar_top_play" />
      <skin id="qgn_graf_mup_npv_prbar_mid_download" />
      <skin id="qgn_graf_mup_npv_prbar_bgd_ls" />
      <skin id="qgn_graf_mup_npv_prbar_bgd" />
      <skin id="qgn_graf_mup_npv_defalbumart" />
      <skin id="qgn_graf_mup_lst_userplayl" />
      <skin id="qgn_graf_mup_lst_track" />
      <skin id="qgn_graf_mup_lst_pdc_title" />
      <skin id="qgn_graf_mup_lst_pdc_partplay" />
      <skin id="qgn_graf_mup_lst_pdc_noplay" />
      <skin id="qgn_graf_mup_lst_pdc_new" />
      <skin id="qgn_graf_mup_lst_pdc_episode" />
      <skin id="qgn_graf_mup_lst_pdc_date" />
      <skin id="qgn_graf_mup_lst_pdc_compplay" />
      <skin id="qgn_graf_mup_lst_pdc_categ" />
      <skin id="qgn_graf_mup_lst_pdc_auto" />
      <skin id="qgn_graf_mup_lst_pdc_added" />
      <skin id="qgn_graf_mup_lst_expd_track" />
      <skin id="qgn_graf_mup_lst_expd_artist" />
      <skin id="qgn_graf_mup_lst_drm_exp" />
      <skin id="qgn_graf_mup_lst_corrupttrack" />
      <skin id="qgn_graf_mup_lst_corruptpodc" />
      <skin id="qgn_graf_mup_lst_colpsd_track" />
      <skin id="qgn_graf_mup_lst_colpsd_artist" />
      <skin id="qgn_graf_mup_lst_brokentrack" />
      <skin id="qgn_graf_mup_lst_brokenpodc" />
      <skin id="qgn_graf_mup_lst_brokenplayl" />
      <skin id="qgn_graf_mup_icon_upnp_remote" />
      <skin id="qgn_graf_mup_dlst_podcast" />
      <skin id="qgn_graf_mup_dlst_nowplaying" />
      <skin id="qgn_graf_mup_dlst_music" />
      <skin id="qgn_graf_mup_ctx_reordersong" />
      <skin id="qgn_graf_mup_ctx_addsong" />
      <!-- End -  Music Player 3 Icons  -->
    </layoutEntity>
    <layoutEntity name="bg_button_pane_pane_cp04@v:0">
      <skin id="qgn_indi_dialer_one" />
      <skin id="qgn_indi_dialer_two" />
      <skin id="qgn_indi_dialer_three" />
      <skin id="qgn_indi_dialer_four" />
      <skin id="qgn_indi_dialer_five" />
      <skin id="qgn_indi_dialer_six" />
      <skin id="qgn_indi_dialer_seven" />
      <skin id="qgn_indi_dialer_eight" />
      <skin id="qgn_indi_dialer_nine" />
      <skin id="qgn_indi_dialer_zero" />
      <skin id="qgn_indi_dialer_prefix" />
      <skin id="qgn_indi_dialer_hash" />
    </layoutEntity>
    <layoutEntity name="bg_popup_call_pane_cp07@v:0">
      <skin id="qgn_graf_call_first_one_held" />
    </layoutEntity>
    <layoutEntity name="wallpaper_pane_g1@V:0">
      <skin id="wallpaper" />
    </layoutEntity>
    <layoutEntity name="main_pane_g1@V:0">
      <skin id="qsn_bg_area_main" />
      <skin id="qsn_bg_area_main_list_gene" />
      <skin id="qsn_bg_area_main_list_set" />
    </layoutEntity>
    <layoutEntity name="main_pane_g1@V:1">
      <skin id="qsn_bg_area_main_idle" />
      <skin id="qgn_graf_call_image_1" />
      <skin id="qgn_graf_nslider_end_left" />
      <skin id="qgn_graf_nslider_end_right" />
      <skin id="qgn_graf_nslider_middle" />
      <skin id="qgn_graf_nslider_marker" />
      <skin id="qgn_graf_nslider_marker_selected" />
      <skin id="qgn_graf_volume_set_off" />
      <skin id="qgn_graf_volume_set_on" />
    </layoutEntity>
    <layoutEntity name="main_pane_g1@V:2">
      <skin id="qsn_bg_area_main_high" />
    </layoutEntity>
    <layoutEntity name="main_pane_g1@V:3">
      <skin id="qsn_bg_area_main_apps_grid" />
    </layoutEntity>
    <layoutEntity name="main_pane_g1@V:4">
      <skin id="qsn_bg_area_main_message" />
    </layoutEntity>
    <layoutEntity name="main_qdial_pane@V:0">
      <skin id="qsn_bg_area_main_qdial" />
    </layoutEntity>
    <layoutEntity name="main_calc_pane@V:0">
      <skin id="qsn_bg_area_main_calc" />
      <skin id="qsn_bg_area_main_pinb" />
    </layoutEntity>
    <layoutEntity name="cell_calc_pane_g2@V:0">
      <skin id="qgn_indi_calc_add" />
      <skin id="qgn_indi_calc_percent" />
      <skin id="qgn_indi_calc_cancel   " />
