=== SymbianSource/oss.FCL.sftools.dev.ui/carbideui/com.nokia.tools.platform.core/src/dtds/preview.dtd
<?xml version='1.0' encoding='us-ascii'?>

<!--THIS FILE SHOULD NOT BE MODIFIED OR DELETED-->

<!--DTD for "preview design"-->

<!ELEMENT Preview (preview_image?)+ >
<!ATTLIST Preview
            name          	CDATA  		#IMPLIED	
            background    	CDATA  		#IMPLIED	
            MasterId	  	CDATA  		#IMPLIED
>


<!ELEMENT preview_image (Element?, reference? )+>


<!ATTLIST preview_image

	    name		CDATA	      	#REQUIRED
	    previewid		CDATA	      	#IMPLIED
	    preview		CDATA	      	#REQUIRED	
	    display		CDATA	      	#IMPLIED	
>

<!ELEMENT Element EMPTY>
<!ATTLIST Element 
	    compName		CDATA       	#REQUIRED
	    skinId		CDATA         	#IMPLIED
	    name		CDATA		#IMPLIED
	    optionId		CDATA         	#IMPLIED
	    varietyId		CDATA         	#REQUIRED		    	
	    level		CDATA         	#IMPLIED
            loc_id		CDATA         	#IMPLIED	            
       	    text		CDATA         	#IMPLIED			    
	    image		CDATA         	#IMPLIED
            is_mask		CDATA         	#IMPLIED	
            mask		CDATA         	#IMPLIED			                
            group		CDATA         	#IMPLIED	
            colourId		CDATA         	#IMPLIED            
            colour		CDATA         	#IMPLIED            
        	shape_link_id	CDATA         	#IMPLIED
            spl_mask_id		CDATA         	#IMPLIED
            scale_mode ( stretch | tile | tile_x | tile_y | aspect_ratio | scale_best | scale_fit | scale_down_fit ) #IMPLIED      			    
	    spl_mask_type	CDATA         	#IMPLIED
	    spl_mask_file	CDATA 	      	#IMPLIED	
	    opacity		CDATA   	#IMPLIED  
	    rotate		CDATA		#IMPLIED          
	    data		CDATA		#IMPLIED
	    text_full	CDATA		#IMPLIED
	    display		CDATA	      	#IMPLIED	
>
<!-- data is for link to additional metadata info system-->

<!ELEMENT reference EMPTY>
<!ATTLIST reference
	    screenName		CDATA       	#REQUIRED
>

=== SymbianSource/oss.FCL.sftools.dev.ui/carbideui/Symbian3/config/screens/360x640/MusicPlayer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Preview SYSTEM "preview.dtd">
<Preview>
  <preview_image display="360x640"
                 name="Music Player"
                 preview="true">
    <Element compName="screen_g1"
             skinId="qsn_bg_screen"
             varietyId="0" />
    <Element compName="status_pane"
             loc_id="&lt;LC&gt;area_top_pane@v:7&lt;/LC&gt;"
             skinId="qsn_fr_status_flat"
             varietyId="1" />
    <Element compName="battery_pane_g1"
             skinId="qgn_indi_battery_strength"
             varietyId="0" />
    <Element compName="signal_pane_g1"
             skinId="qgn_indi_signal_strength"
             varietyId="0" />
    <Element colourId="icon5"
             compName="signal_pane_g2"
             image="qgn_prop_signal_icon.svg"
             varietyId="0" />
    <Element colourId="icon6"
             compName="battery_pane_g2"
             image="qgn_prop_battery_icon.svg"
             varietyId="0" />
	<Element colourId="text6"
			compName="main_mup2_t3"
             text="2/2"
             varietyId="0" />
	<Element colourId="text13"
             compName="control_pane_t1"
             loc_id="&lt;LC&gt;area_bottom_pane@v:0&lt;/LC&gt;"
             text="Options"
             varietyId="4" />
    <Element colourId="text14"
             compName="control_pane_t2"
             loc_id="&lt;LC&gt;area_bottom_pane@v:0&lt;/LC&gt;"
             text="Back"
             varietyId="4" />
    <Element compName="popup_mup3_control_window"
             display="360x640"
             loc_id="&lt;LC&gt;application_window@v:0&lt;/LC&gt;&lt;LC&gt;main_pane@v:20&lt;/LC&gt;&lt;LC&gt;main_mup3_pane@v:0&lt;/LC&gt;"
             skinId="qgn_indi_mup_default_album"
             varietyId="0" />
    <Element compName="main_mup_bar_pane"
             display="360x640"
             skinId="qgn_graf_mup2_bar_frame"
             varietyId="0" />
    <Element colourId="text6"
             compName="main_mup2_pane_t2"
             loc_id="&lt;LC&gt;main_pane@v:15&lt;/LC&gt;&lt;LC&gt;main_mup2_pane@v:0&lt;/LC&gt;"
             text="sample"
             varietyId="1" />
    <Element colourId="text6"
             compName="main_mup2_t1"
             text="00:00"
             varietyId="0" />
    <Element colourId="text6"
             compName="main_mup2_t2"
             text="00:04"
             varietyId="0" />
    <Element colourId="text6"
             compName="main_mup2_pane_t3"
             loc_id="&lt;LC&gt;main_pane@v:15&lt;/LC&gt;&lt;LC&gt;main_mup2_pane@v:0&lt;/LC&gt;"
             text="Unknown artist"
             varietyId="1" />
    <reference screenName="TouchPaneButtons" />
    <Element compName="cell_sctrl_middle_pane_g2"
             skinId="qgn_prop_image_tb_prev"
             varietyId="1" />
    <Element compName="cell_sctrl_middle_pane_g2"
             loc_id="&lt;LC&gt;grid_sctrl_middle_pane@v:1&lt;/LC&gt;&lt;LC&gt;cell_sctrl_middle_pane@v:1#r:1#c:2&lt;/LC&gt;"
             skinId="qgn_prop_image_tb_pause"
             varietyId="1" />
    <Element compName="cell_sctrl_middle_pane_g2"
             loc_id="&lt;LC&gt;grid_sctrl_middle_pane@v:1&lt;/LC&gt;&lt;LC&gt;cell_sctrl_middle_pane@v:1#r:1#c:3&lt;/LC&gt;"
             skinId="qgn_prop_image_tb_next"
             varietyId="1" />
    <Element compName="main_mup3_pane_t5"
             loc_id="&lt;LC&gt;area_bottom_pane@v:0&lt;/LC&gt;&lt;LC&gt;main_pane@v:0&lt;/LC&gt;"
             text="1/2"
             varietyId="8" />
    <Element compName="control_pane_g3"
             display="!360x640"
             skinId="qsn_bg_area_control"
             varietyId="0" />
    <Element compName="control_pane_g3"
             display="360x640"
             loc_id="&lt;LC&gt;area_bottom_pane@v:0&lt;/LC&gt;"
             skinId="qsn_bg_area_control"
             varietyId="0" />
    <reference screenName="BaseSoftkeys" />
    <Element colourId="text13"
             compName="control_pane_t1"
             loc_id="&lt;LC&gt;area_bottom_pane@v:0&lt;/LC&gt;"
             text="Options"
             varietyId="4" />
    <Element colourId="text14"
             compName="control_pane_t2"
             loc_id="&lt;LC&gt;area_bottom_pane@v:0&lt;/LC&gt;"
             text="Back"
             varietyId="4" />
    <Element colourId="text1"
             compName="title_pane_t1"
             text="Now Playing"
             varietyId="5" />
  </preview_image>

</Preview>

=== SymbianSource/oss.FCL.sftools.dev.ui/carbideui/Symbian3/config/screens/360x640/CallDialling.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Preview SYSTEM "preview.dtd">
<Preview>
	<preview_image display="360x640" name="Call Dialling"
		preview="true">
		<reference screenName="BaseScreen4" />
		<reference screenName="TouchPaneHorizontal0" />
		<!-- <reference screenName="VolumeIndicatorPortrait" /> -->
		<!-- <reference screenName="NaviArrowPortrait" /> -->
		<reference screenName="BaseScreenCall2" />
		<!-- <reference screenName="BaseScreen17" /> -->
		<!--  <Element colourId="icon5" compName="signal_pane_g2" display="360x640"
			image="qgn_prop_signal_icon.svg" varietyId="0" />
		<Element colourId="icon6" compName="battery_pane_g2" display="360x640"
			image="qgn_prop_battery_icon.svg" varietyId="0" />-->
		<!-- analogue clock -->
		<Element compName="popup_clock_analogue_window_g1" skinId="qsn_cp_clock_analogue_face_1"
			varietyId="0" />
		<Element compName="popup_clock_analogue_window_g2" skinId="qsn_cp_clock_analogue_border_num"
			varietyId="0" />
		<Element compName="popup_clock_analogue_window_g3" skinId="qsn_cp_clock_analogue_pointer_hour"
			varietyId="0" />
		<Element compName="popup_clock_analogue_window_g4" skinId="qsn_cp_clock_analogue_pointer_minute"
			varietyId="0" />
		<Element colourId="icon1" compName="popup_clock_analogue_window_t1"
			text="01" varietyId="0" />
		<Element compName="popup_clock_analogue_window_g5" skinId="qsn_cp_clock_analogue_face_2"
			varietyId="0" />
		<Element colourId="text2" compName="navi_text_pane_t1"
			display="!360x640" loc_id="&lt;LC&gt;navi_pane@v:6&lt;/LC&gt;" text="We 01/08/2007"
			varietyId="0" />
		<Element colourId="text2" compName="navi_text_pane_t1"
			display="360x640"
			loc_id="&lt;LC&gt;application_window@v:0&lt;/LC&gt;&lt;LC&gt;area_top_pane@v:16&lt;/LC&gt;&lt;LC&gt;navi_pane@v:6&lt;/LC&gt;"
			text="We 01/08/2007" varietyId="0" />
		<!-- <Element colourId="text36" compName="title_pane_t1"
			loc_id="&lt;LC&gt;title_pane@v:1&lt;/LC&gt;" text="Operator"
			varietyId="0" /> -->
		<!-- contents of main pane -->
		<!-- <Element compName="call4_image_pane"
			loc_id="&lt;LC&gt;application_window@v:0&lt;/LC&gt;&lt;LC&gt;main_pane@v:18&lt;/LC&gt;&lt;LC&gt;main_call4_pane@v:0&lt;/LC&gt;"
			skinId="qgn_graf_call_image_1" varietyId="2" /> -->
			
		<Element compName="popup_call4_audio_in_window" display="360x640"
			loc_id="&lt;LC&gt;application_window@v:0&lt;/LC&gt;&lt;LC&gt;main_pane@v:18&lt;/LC&gt;&lt;LC&gt;main_call4_pane@v:0&lt;/LC&gt;&lt;LC&gt;call4_windows_pane@v:2&lt;/LC&gt;"
			skinId="qsn_fr_call2_rect" varietyId="4" />
		<Element colourId="text51" compName="popup_call_audio_in_window_t1"
			display="360x640"
			loc_id="&lt;LC&gt;application_window@v:0&lt;/LC&gt;&lt;LC&gt;main_pane@v:18&lt;/LC&gt;&lt;LC&gt;main_call4_pane@v:0&lt;/LC&gt;&lt;LC&gt;call4_windows_pane@v:2&lt;/LC&gt;&lt;LC&gt;popup_call4_audio_in_window@v:4&lt;/LC&gt;"
			text="+3589123456789" varietyId="0" />
		<Element colourId="text51" compName="popup_call_audio_in_window_t2"
			display="360x640"
			loc_id="&lt;LC&gt;application_window@v:0&lt;/LC&gt;&lt;LC&gt;main_pane@v:18&lt;/LC&gt;&lt;LC&gt;main_call4_pane@v:0&lt;/LC&gt;&lt;LC&gt;call4_windows_pane@v:2&lt;/LC&gt;&lt;LC&gt;popup_call4_audio_in_window@v:4&lt;/LC&gt;"
			text="calling" varietyId="0" />
		<Element compName="popup_call_status_window_g2" image="qgn_indi_call_active.svg" display="360x640"
			loc_id="&lt;LC&gt;application_window@v:0&lt;/LC&gt;&lt;LC&gt;main_pane@v:18&lt;/LC&gt;&lt;LC&gt;main_call4_pane@v:0&lt;/LC&gt;&lt;LC&gt;call4_windows_pane@v:2&lt;/LC&gt;&lt;LC&gt;popup_call4_audio_in_window@v:4&lt;/LC&gt;"
			varietyId="0" />
    <Element compName="bg_button_pane_cp09"
             display="360x640"
             skinId="qsn_fr_button_normal"
             loc_id="&lt;LC&gt;application_window@v:0&lt;/LC&gt;&lt;LC&gt;main_pane@v:18&lt;/LC&gt;&lt;LC&gt;main_call4_pane@v:0&lt;/LC&gt;&lt;LC&gt;grid_call4_button_pane@v:2&lt;/LC&gt;&lt;LC&gt;cell_call4_button_pane@v:0&lt;/LC&gt;"
             varietyId="0" />
    <Element compName="bg_button_pane_cp09"
             display="360x640"
             skinId="qsn_fr_button_normal_reject"
 			 loc_id="&lt;LC&gt;application_window@v:0&lt;/LC&gt;&lt;LC&gt;main_pane@v:18&lt;/LC&gt;&lt;LC&gt;main_call4_pane@v:0&lt;/LC&gt;&lt;LC&gt;grid_call4_button_pane@v:2&lt;/LC&gt;&lt;LC&gt;cell_call4_button_pane@#r:1#c:2&lt;/LC&gt;"
             varietyId="0" />
		<!-- <Element compName="bg_button_pane_cp09" image="qgn_graf_bg_touch_horizontal.svg" display="360x640"
			loc_id="&lt;LC&gt;application_window@v:0&lt;/LC&gt;&lt;LC&gt;main_pane@v:18&lt;/LC&gt;&lt;LC&gt;main_call4_pane@v:0&lt;/LC&gt;&lt;LC&gt;grid_call4_button_pane@v:2&lt;/LC&gt;&lt;LC&gt;cell_call4_button_pane@v:0&lt;/LC&gt;"
			skinId="bg_popup_sub_pane_cp2" varietyId="0" /> 
		<Element compName="bg_button_pane_cp09" image="qgn_graf_bg_touch_horizontal.svg" display="360x640"
			loc_id="&lt;LC&gt;application_window@v:0&lt;/LC&gt;&lt;LC&gt;main_pane@v:18&lt;/LC&gt;&lt;LC&gt;main_call4_pane@v:0&lt;/LC&gt;&lt;LC&gt;grid_call4_button_pane@v:2&lt;/LC&gt;&lt;LC&gt;cell_call4_button_pane@#r:1#c:2&lt;/LC&gt;"
			skinId="bg_popup_sub_pane_cp2" varietyId="0" />-->
		<Element compName="cell_call4_button_pane_g1" display="360x640"
			loc_id="&lt;LC&gt;application_window@v:0&lt;/LC&gt;&lt;LC&gt;main_pane@v:18&lt;/LC&gt;&lt;LC&gt;main_call4_pane@v:0&lt;/LC&gt;&lt;LC&gt;grid_call4_button_pane@v:2&lt;/LC&gt;&lt;LC&gt;cell_call4_button_pane@v:0&lt;/LC&gt;"
			skinId="qgn_indi_button_loudspeaker" varietyId="0" />
		<Element compName="cell_call4_button_pane_g1"
			loc_id="&lt;LC&gt;application_window@v:0&lt;/LC&gt;&lt;LC&gt;main_pane@v:18&lt;/LC&gt;&lt;LC&gt;main_call4_pane@v:0&lt;/LC&gt;&lt;LC&gt;grid_call4_button_pane@v:2&lt;/LC&gt;&lt;LC&gt;cell_call4_button_pane@#r:1#c:2&lt;/LC&gt;"
			skinId="qgn_indi_button_end_active_call" varietyId="0" />
		<Element colourId="text82" compName="cell_call4_button_pane_t1" display="360x640"
			loc_id="&lt;LC&gt;application_window@v:0&lt;/LC&gt;&lt;LC&gt;main_pane@v:18&lt;/LC&gt;&lt;LC&gt;main_call4_pane@v:0&lt;/LC&gt;&lt;LC&gt;grid_call4_button_pane@v:2&lt;/LC&gt;&lt;LC&gt;cell_call4_button_pane@v:0&lt;/LC&gt;"
			text="Loud Speaker" varietyId="0" />
		<Element colourId="text83" compName="cell_call4_button_pane_t1"
			loc_id="&lt;LC&gt;application_window@v:0&lt;/LC&gt;&lt;LC&gt;main_pane@v:18&lt;/LC&gt;&lt;LC&gt;main_call4_pane@v:0&lt;/LC&gt;&lt;LC&gt;grid_call4_button_pane@v:2&lt;/LC&gt;&lt;LC&gt;cell_call4_button_pane@#r:1#c:2&lt;/LC&gt;"
			text="End call" varietyId="0" />
			
		<!-- touch pane -->
		<reference screenName="TouchPaneButtons" />
		<Element compName="cell_sctrl_middle_pane_g2" display="360x640"
			loc_id="&lt;LC&gt;grid_sctrl_middle_pane@v:1&lt;/LC&gt;&lt;LC&gt;cell_sctrl_middle_pane@v:1#r:1#c:3&lt;/LC&gt;"
			skinId="qgn_indi_button_loudspeaker" varietyId="1" />
		<Element compName="cell_sctrl_middle_pane_g2" display="360x640"
			loc_id="&lt;LC&gt;grid_sctrl_middle_pane@v:1&lt;/LC&gt;&lt;LC&gt;cell_sctrl_middle_pane@v:1#r:1#c:2&lt;/LC&gt;"
			skinId="qgn_indi_button_mute_mic" varietyId="1" />
		<Element compName="cell_sctrl_middle_pane_g2" display="360x640"
			skinId="qgn_indi_dialer_contacts" varietyId="1" />
			
		<!--Contents of control pane-->
		<reference screenName="BaseSoftkeys" />	
		<Element colourId="text15" compName="control_pane_t1"
			loc_id="&lt;LC&gt;area_bottom_pane@v:0&lt;/LC&gt;" text="Options"
			varietyId="4" />
		<Element colourId="text16" compName="control_pane_t2"
			loc_id="&lt;LC&gt;area_bottom_pane@v:0&lt;/LC&gt;" text="Silence"
			varietyId="4" />
	</preview_image>
</Preview>

=== SymbianSource/oss.FCL.sftools.dev.ui/carbideui/Symbian3/config/screens/360x640/VirtualKeyboard.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Preview SYSTEM "preview.dtd">
<Preview>
	<preview_image display="360x640"
                 name="Virtual Keyboard"
                 preview="false">
    <reference screenName="Message Editor" />
    
    <Element colourId="icon4" compName="navi_icon_pane_g1" display="360x640" image="ts_qgn_stat_case_text.svg" loc_id="&lt;LC&gt;status_pane@v:0&lt;/LC&gt;&lt;LC&gt;navi_pane@v:4&lt;/LC&gt;&lt;LC&gt;navi_icon_pane@v:0&lt;/LC&gt;" varietyId="0"/>
    
    <Element compName="vkb2_top_grid_right_pane_g1"
             skinId="qsn_fr_function_button_normal"
             varietyId="4" />
    <Element colourId="icon30"
             compName="vkb2_top_cell_right_wide_pane_g1"
             image="qgn_indi_input_backspace.svg"
             loc_id="&lt;LC&gt;vkb2_top_grid_right_pane_g1@v:4&lt;/LC&gt;"
             varietyId="4" />
    <Element compName="vkb2_top_grid_right_pane_g4"
             skinId="qsn_fr_function_button_normal"
             varietyId="4" />
    <Element colourId="icon30"
             compName="vkb2_top_cell_right_wide_pane_g1"
             image="qgn_indi_input_move.svg"
             loc_id="&lt;LC&gt;vkb2_top_cell_right_wide_pane@v:4&lt;/LC&gt;"
             varietyId="4" />
    <Element compName="vkb2_top_entry_pane_g1"
             skinId="qgn_graf_fep_input_bg"
             varietyId="4" />
    <Element colourId="text60"
             compName="vkb2_top_entry_pane_t1"
             text="QWERTY"
             varietyId="4" />
    <Element colourId="text60"
             compName="vkb2_top_entry_pane_t2"
             text="VIRTUAL KEYBOARD"
             varietyId="4" />
    <Element compName="bg_vkb2_func_pane"
             skinId="qsn_fr_function_button_normal"
             varietyId="4" />
    <Element compName="vkb2_top_cell_left_pane_g1"
             loc_id="&lt;LC&gt;bg_vkb2_func_pane@v:4&lt;/LC&gt;"
             image="qgn_indi_itut_close.svg"
             varietyId="4" />
    <Element compName="bg_vkb2_func_pane"
             loc_id="&lt;LC&gt;vkb2_top_cell_left_pane@v:4#r:2#c:1&lt;/LC&gt;"
             skinId="qsn_fr_function_button_normal"
             varietyId="4" />
    <Element colourId="icon30"
             compName="vkb2_top_cell_left_pane_g1"
             image="qgn_indi_itut_options.svg"
             loc_id="&lt;LC&gt;vkb2_top_cell_left_pane@v:4#r:2#c:1&lt;/LC&gt;"
             varietyId="4" />
    <reference screenName="VKBKeypadArea" />
    <reference screenName="VKBpptbottom" />
    <reference screenName="VKBpptBottomScreenn" />
    <Element compName="bg_popup_fep_char_preview_window"
             loc_id="&lt;LC&gt;vkb2_row_keypad_pane@v:0#r:1#c:1&lt;/LC&gt;&lt;LC&gt;vkb2_cell_t_keypad_pane@v:0#r:1#c:1&lt;/LC&gt;"
             skinId="qsn_fr_input_char_preview"
             varietyId="4" />
    <Element colourId="text60"
             compName="popup_fep_char_preview_window_t1"
             loc_id="&lt;LC&gt;vkb2_row_keypad_pane@v:0#r:1#c:1&lt;/LC&gt;&lt;LC&gt;vkb2_cell_t_keypad_pane@v:0#r:1#c:1&lt;/LC&gt;"
             text="A"
             varietyId="4" />
  </preview_image>
 
</Preview>
