=== SymbianSource/oss.FCL.sftools.dev.ui/carbideui/com.nokia.tools.platform.core/src/dtds/preview.dtd
<?xml version='1.0' encoding='us-ascii'?>

<!--THIS FILE SHOULD NOT BE MODIFIED OR DELETED-->

<!--DTD for "preview design"-->

<!ELEMENT Preview (preview_image?)+ >
<!ATTLIST Preview
            name          	CDATA  		#IMPLIED	
            background    	CDATA  		#IMPLIED	
            MasterId	  	CDATA  		#IMPLIED
>


<!ELEMENT preview_image (Element?, reference? )+>


<!ATTLIST preview_image

	    name		CDATA	      	#REQUIRED
	    previewid		CDATA	      	#IMPLIED
	    preview		CDATA	      	#REQUIRED	
	    display		CDATA	      	#IMPLIED	
>

<!ELEMENT Element EMPTY>
<!ATTLIST Element 
	    compName		CDATA       	#REQUIRED
	    skinId		CDATA         	#IMPLIED
	    name		CDATA		#IMPLIED
	    optionId		CDATA         	#IMPLIED
	    varietyId		CDATA         	#REQUIRED		    	
	    level		CDATA         	#IMPLIED
            loc_id		CDATA         	#IMPLIED	            
       	    text		CDATA         	#IMPLIED			    
	    image		CDATA         	#IMPLIED
            is_mask		CDATA         	#IMPLIED	
            mask		CDATA         	#IMPLIED			                
            group		CDATA         	#IMPLIED	
            colourId		CDATA         	#IMPLIED            
            colour		CDATA         	#IMPLIED            
        	shape_link_id	CDATA         	#IMPLIED
            spl_mask_id		CDATA         	#IMPLIED
            scale_mode ( stretch | tile | tile_x | tile_y | aspect_ratio | scale_best | scale_fit | scale_down_fit ) #IMPLIED      			    
	    spl_mask_type	CDATA         	#IMPLIED
	    spl_mask_file	CDATA 	      	#IMPLIED	
	    opacity		CDATA   	#IMPLIED  
	    rotate		CDATA		#IMPLIED          
	    data		CDATA		#IMPLIED
	    text_full	CDATA		#IMPLIED
	    display		CDATA	      	#IMPLIED	
>
<!-- data is for link to additional metadata info system-->

<!ELEMENT reference EMPTY>
<!ATTLIST reference
	    screenName		CDATA       	#REQUIRED
>

=== SymbianSource/oss.FCL.sftools.dev.ui/carbideui/Symbian3/config/screens/360x640/SettingsMenu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Preview SYSTEM "preview.dtd">
<Preview>
	<preview_image display="portrait,square" name="Settings Menu"
		preview="true">
		<reference screenName="BaseScreen0" />
		<reference screenName="TouchPaneHorizontal0" />
		<reference screenName="MainScrollBar0" />

		<Element colourId="text56" compName="control_pane_t3" display="!360x640"
			text="Open" varietyId="3" />

		<!-- main area contents -->
		<Element compName="bg_list_pane_g1" display="!360x640" skinId="qsn_bg_column_AB"
			varietyId="2" />
		<Element compName="bg_list_pane_g1" display="360x640"
			loc_id="&lt;LC&gt;application_window@v:0&lt;/LC&gt;&lt;LC&gt;main_pane@v:8&lt;/LC&gt;&lt;LC&gt;bg_list_pane@v:0&lt;/LC&gt;"
			skinId="qsn_bg_column_AB" varietyId="2" />

		<!--
			<Element skinId="qsn_bg_slice_list_AB" compName="bg_list_pane_g3"
			varietyId="2" /> <Element
			skinId="qgn_graf_line_primary_vertical_dashed"
			compName="bg_list_pane_g4" varietyId="2" /> <Element
			skinId="qgn_graf_line_primary_horizontal_dashed"
			compName="bg_list_pane_g5" varietyId="2" />
		-->

		<Element colourId="text1" compName="title_pane_t1" text="Settings"
			varietyId="5" />

		<reference screenName="FourTabPortrait" />
		<Element colourId="icon9" compName="tabs_4_1_passive_pane_g1"
			display="!360x640" image="qgn_prop_set_apps_tab4.svg"
			loc_id="&lt;LC&gt;navi_pane@v:5&lt;/LC&gt;&lt;LC&gt;navi_navi_pane@v:0&lt;/LC&gt;&lt;LC&gt;tabs_4_passive_pane_cp2@v:0&lt;/LC&gt;"
			varietyId="0" />
		<Element colourId="icon9" compName="tabs_4_1_passive_pane_g1"
			display="!360x640" image="qgn_prop_set_conn_tab4.svg"
			loc_id="&lt;LC&gt;navi_pane@v:5&lt;/LC&gt;&lt;LC&gt;navi_navi_pane@v:0&lt;/LC&gt;&lt;LC&gt;tabs_4_passive_pane@v:1&lt;/LC&gt;"
			varietyId="0" />
		<Element colourId="icon9" compName="tabs_4_1_passive_pane_g1"
			display="!360x640" image="qgn_prop_set_call_tab4.svg"
			loc_id="&lt;LC&gt;navi_pane@v:5&lt;/LC&gt;&lt;LC&gt;navi_navi_pane@v:0&lt;/LC&gt;&lt;LC&gt;tabs_4_passive_pane_cp@v:0&lt;/LC&gt;"
			varietyId="0" />
		<Element colourId="icon8" compName="tabs_4_active_pane_g1"
			display="!360x640" image="qgn_prop_set_gene_tab4.svg"
			loc_id="&lt;LC&gt;navi_pane@v:5&lt;/LC&gt;&lt;LC&gt;navi_navi_pane@v:0&lt;/LC&gt;&lt;LC&gt;tabs_4_active_pane@v:0&lt;/LC&gt;"
			varietyId="0" />

		<!--application content-->
		<Element compName="list_highlight_pane_cp1" display="!360x640"
			loc_id="&lt;LC&gt;list_single_large_graphic_pane@v:0#r:1&lt;/LC&gt;"
			skinId="S60_2_6%qsn_fr_list" varietyId="0" />
		<Element compName="list_single_large_graphic_pane_g1" display="!360x640"
			loc_id="&lt;LC&gt;list_single_large_graphic_pane@v:0#r:1&lt;/LC&gt;"
			skinId="qgn_prop_set_gene_psln" varietyId="0" />
		<Element colourId="text10" compName="list_single_large_graphic_pane_t1"
			display="!360x640" loc_id="&lt;LC&gt;list_single_large_graphic_pane@v:0#r:1&lt;/LC&gt;"
			text="Personalisation" varietyId="0" />
		<Element compName="list_single_large_graphic_pane_g1" display="!360x640"
			loc_id="&lt;LC&gt;list_single_large_graphic_pane@v:0#r:2&lt;/LC&gt;"
			skinId="qgn_prop_set_datim_sub" varietyId="0" />
		<Element colourId="text6" compName="list_single_large_graphic_pane_t1"
			display="!360x640" loc_id="&lt;LC&gt;list_single_large_graphic_pane@v:0#r:2&lt;/LC&gt;"
			text="Date &amp; Time" varietyId="0" />
		<Element compName="list_single_large_graphic_pane_g1" display="!360x640"
			loc_id="&lt;LC&gt;list_single_large_graphic_pane@v:0#r:3&lt;/LC&gt;"
			skinId="qgn_prop_set_accessory_sub" varietyId="0" />
		<Element colourId="text6" compName="list_single_large_graphic_pane_t1"
			display="!360x640" loc_id="&lt;LC&gt;list_single_large_graphic_pane@v:0#r:3&lt;/LC&gt;"
			text="Accessory" varietyId="0" />
		<Element compName="list_single_large_graphic_pane_g1" display="!360x640"
			loc_id="&lt;LC&gt;list_single_large_graphic_pane@v:0#r:4&lt;/LC&gt;"
			skinId="qgn_prop_set_sec_sub" varietyId="0" />
		<Element colourId="text6" compName="list_single_large_graphic_pane_t1"
			display="!360x640" loc_id="&lt;LC&gt;list_single_large_graphic_pane@v:0#r:4&lt;/LC&gt;"
			text="Security" varietyId="0" />
		<Element compName="list_single_large_graphic_pane_g1" display="!360x640"
			loc_id="&lt;LC&gt;list_single_large_graphic_pane@v:0#r:5&lt;/LC&gt;"
			skinId="qgn_prop_set_gene_phone" varietyId="0" />
		<Element colourId="text6" compName="list_single_large_graphic_pane_t1"
			display="!360x640" loc_id="&lt;LC&gt;list_single_large_graphic_pane@v:0#r:5&lt;/LC&gt;"
			text="Original Settings" varietyId="0" />

		<Element compName="list_highlight_pane_cp1" display="360x640"
			loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_single_large_graphic_pane@v:0&lt;/LC&gt;"
			skinId="S60_2_6%qsn_fr_list" varietyId="0" />
		<Element compName="list_single_large_graphic_pane_g1" display="360x640"
			loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_single_large_graphic_pane@v:0&lt;/LC&gt;"
			skinId="qgn_prop_cp_perso_prof" varietyId="0" />
		<Element colourId="text10" compName="list_single_large_graphic_pane_t1"
			display="360x640"
			loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_single_large_graphic_pane@v:0&lt;/LC&gt;"
			text="Profiles" varietyId="0" />
		<Element compName="list_single_large_graphic_pane_g1" display="360x640"
			loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_single_large_graphic_pane@#r:2#c:1&lt;/LC&gt;"
			skinId="qgn_prop_set_gene_psln" varietyId="0" />
		<Element colourId="text6" compName="list_single_large_graphic_pane_t1"
			display="360x640"
			loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_single_large_graphic_pane@#r:2#c:1&lt;/LC&gt;"
			text="Themes" varietyId="0" />
		<Element compName="list_single_large_graphic_pane_g1" display="360x640"
			loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_single_large_graphic_pane@#r:3#c:1&lt;/LC&gt;"
			skinId="qgn_prop_cp_dev" varietyId="0" />
		<Element colourId="text6" compName="list_single_large_graphic_pane_t1"
			display="360x640"
			loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_single_large_graphic_pane@#r:3#c:1&lt;/LC&gt;"
			text="Phone" varietyId="0" />
		<Element compName="list_single_large_graphic_pane_g1" display="360x640"
			loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_single_large_graphic_pane@#r:4#c:1&lt;/LC&gt;"
			skinId="qgn_prop_cp_inst" varietyId="0" />
		<Element colourId="text6" compName="list_single_large_graphic_pane_t1"
			display="360x640"
			loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_single_large_graphic_pane@#r:4#c:1&lt;/LC&gt;"
			text="Application mgr." varietyId="0" />
		<Element compName="list_single_large_graphic_pane_g1" display="360x640"
			loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_single_large_graphic_pane@#r:5#c:1&lt;/LC&gt;"
			skinId="qgn_prop_cp_tele" varietyId="0" />
		<Element colourId="text6" compName="list_single_large_graphic_pane_t1"
			display="360x640"
			loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_single_large_graphic_pane@#r:5#c:1&lt;/LC&gt;"
			text="Calling" varietyId="0" />
		<Element compName="list_single_large_graphic_pane_g1" display="360x640"
			loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_single_large_graphic_pane@#r:6#c:1&lt;/LC&gt;"
			skinId="qgn_prop_cp_conn_shortcut" varietyId="0" />
		<Element colourId="text6" compName="list_single_large_graphic_pane_t1"
			display="360x640"
			loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_single_large_graphic_pane@#r:6#c:1&lt;/LC&gt;"
			text="Connectivity" varietyId="0" />
		<Element compName="list_single_large_graphic_pane_g1" display="360x640"
			loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_single_large_graphic_pane@#r:7#c:1&lt;/LC&gt;"
			skinId="qgn_prop_set_apps_sub" varietyId="0" />
		<Element colourId="text6" compName="list_single_large_graphic_pane_t1"
			display="360x640"
			loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_single_large_graphic_pane@#r:7#c:1&lt;/LC&gt;"
			text="Application sett." varietyId="0" />
		<reference screenName="BaseSoftkeys" />		
        <Element colourId="text13"
             compName="control_pane_t1"
             loc_id="&lt;LC&gt;area_bottom_pane@v:0&lt;/LC&gt;"
             text="Options"
             varietyId="4" />
    <Element colourId="text14"
             compName="control_pane_t2"
             loc_id="&lt;LC&gt;area_bottom_pane@v:0&lt;/LC&gt;"
             text="Exit"
             varietyId="4" />
	</preview_image>
</Preview>

=== SymbianSource/oss.FCL.sftools.dev.ui/carbideui/Symbian3/config/screens/640x360/Homescreen.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE Preview SYSTEM "preview.dtd">
<Preview MasterId="70" name="Home Screen Lsc">
<preview_image display="landscape" name="Home Screen" preview="true">
    <reference screenName="BaseScreen11" />
    <Element colourId="text37"
             compName="title_pane_stacon_t1"
             loc_id="&lt;LC&gt;area_top_pane@v:2&lt;/LC&gt;&lt;LC&gt;stacon_top_pane@v:0&lt;/LC&gt;&lt;LC&gt;title_pane_stacon@v:0&lt;/LC&gt;"
             text="Operator"
             varietyId="0" />
    <Element compName="hs_widget_clock_background" skinId="qgn_home_bg_widget" varietyId="0"/>
        <Element compName="hs_widget_background_p1" skinId="qgn_home_bg_widget" varietyId="0"/>
        <Element compName="hs_widget_background_t1" skinId="text75" text="Wed 12/03/08" varietyId="0"/>
        <Element compName="hs_widget_background_p2" skinId="qgn_home_bg_widget" varietyId="0"/>
        <Element compName="hs_widget_background_t2" skinId="text75" text="General" varietyId="0"/>
        <Element compName="hs_widget_background_g2" skinId="qgn_indi_home_profile_general" varietyId="0"/>
        <Element compName="hs_widget_background_p3" skinId="qgn_home_bg_widget" varietyId="0"/>
        <!-- <Element compName="hs_widget_background_p4" skinId="qgn_home_bg_widget" varietyId="0"/> -->
    	<Element compName="hs_widget_background_g3"
             image="qgn_menu_cale.svg"
             loc_id="&lt;LC&gt;hs_widget_background_p3@v:0#r:1&lt;/LC&gt;"
             varietyId="0" />
    	<Element colourId="text75"
             compName="hs_widget_background_t3"
             loc_id="&lt;LC&gt;hs_widget_background_p3@v:0#r:1&lt;/LC&gt;"
             text="Yahoo! (12)"
             varietyId="0" />
    	<Element compName="hs_widget_background_g3"
             image="qgn_indi_ai_eplg_read.svg"
             loc_id="&lt;LC&gt;hs_widget_background_p3@v:0#r:2&lt;/LC&gt;"
             varietyId="0" />
    	<Element colourId="text75"
             compName="hs_widget_background_t3"
             loc_id="&lt;LC&gt;hs_widget_background_p3@v:0#r:2&lt;/LC&gt;"
             text="Jack.Ryan Meeting ab ..."
             varietyId="0" />
    	<Element compName="hs_widget_background_g3"
             image="qgn_indi_ai_eplg_read.svg"
             loc_id="&lt;LC&gt;hs_widget_background_p3@v:0#r:3&lt;/LC&gt;"
             varietyId="0" />
    	<Element colourId="text75"
             compName="hs_widget_background_t3"
             loc_id="&lt;LC&gt;hs_widget_background_p3@v:0#r:3&lt;/LC&gt;"
             text="Jack Spa... Invitatio ..."
             varietyId="0" />
        <Element compName="hs_widget_background_p3" skinId="qsn_fr_home" varietyId="0"/>
        <Element compName="hs_widget_background_p5" skinId="qgn_menu_browser" loc_id="&lt;LC&gt;hs_widget_background_p5@v:0#r:1#c:1&lt;/LC&gt;" varietyId="0"/>
        <Element compName="hs_widget_background_p5" skinId="qgn_menu_mce_cxt" loc_id="&lt;LC&gt;hs_widget_background_p5@v:0#r:1#c:2&lt;/LC&gt;" varietyId="0"/>
        <Element compName="hs_widget_background_p5" skinId="qgn_menu_phob_cxt" loc_id="&lt;LC&gt;hs_widget_background_p5@v:0#r:1#c:3&lt;/LC&gt;" varietyId="0"/>
        <Element compName="hs_widget_background_p5" skinId="qgn_menu_log_cxt" loc_id="&lt;LC&gt;hs_widget_background_p5@v:0#r:1#c:4&lt;/LC&gt;" varietyId="0"/>
        <Element compName="hs_widget_background_p16" skinId="qgn_home_bg_widget" varietyId="0"/>
        <Element compName="hs_widget_background_p17" skinId="qgn_home_button_widget" varietyId="0"/>
    	<Element colourId="text75"
             compName="hs_widget_background_p16_t1"
             text="Shakira - Hips don't Lie"
             varietyId="0" />
        <Element compName="hs_widget_background_p18" skinId="qgn_home_button_widget" varietyId="0"/>
        <Element compName="hs_widget_background_p19" skinId="qgn_home_button_widget" varietyId="0"/>
        <Element compName="hs_widget_background_p20" skinId="qgn_home_button_widget" varietyId="0"/>
    <Element compName="hs_widget_background_p18"
             skinId="qgn_prop_image_tb_prev"
             varietyId="0" />
    <Element compName="hs_widget_background_p19"
             skinId="qgn_prop_image_tb_play2"
             varietyId="0" />
    <Element compName="hs_widget_background_p20"
             skinId="qgn_prop_image_tb_next"
             varietyId="0" />
        <Element compName="hs_widget_background_p7" skinId="qgn_home_bg_widget" varietyId="0"/>
        <Element compName="hs_widget_background_p8" skinId="qgn_home_button_widget" varietyId="0"/>
        <Element compName="hs_widget_background_p9" skinId="qgn_home_button_widget" varietyId="0"/>
        <Element compName="hs_widget_background_p10" skinId="qgn_home_button_widget" varietyId="0"/>
        <Element compName="hs_widget_background_p11" skinId="qgn_home_button_widget" varietyId="0"/>
		<Element compName="hs_widget_background_p8" display="640x360"
			image="qgn_prop_home_default_friend.svg"
			varietyId="0" />
		<Element compName="hs_widget_background_p9" display="640x360"
			image="qgn_prop_home_default_friend.svg"
			varietyId="0" />
		<Element compName="hs_widget_background_p10" display="640x360"
			image="qgn_prop_home_default_friend.svg"
			varietyId="0" />
		<Element compName="hs_widget_background_p11" display="640x360"
			image="qgn_prop_home_default_friend.svg"
			varietyId="0" />
        <Element compName="hs_widget_background_p12" skinId="qgn_home_contactname_bg" varietyId="0"/>
        <Element compName="hs_widget_background_p13" skinId="qgn_home_contactname_bg" varietyId="0"/>
        <Element compName="hs_widget_background_p14" skinId="qgn_home_contactname_bg" varietyId="0"/>
        <Element compName="hs_widget_background_p15" skinId="qgn_home_contactname_bg" varietyId="0"/>
    	<Element colourId="text75"
             compName="hs_widget_background_p12_t1"
             text="Walker"
             varietyId="0" />
    	<Element colourId="text75"
             compName="hs_widget_background_p13_t1"
             text="Julian..."
             varietyId="0" />
    	<Element colourId="text75"
             compName="hs_widget_background_p14_t1"
             text="Minna"
             varietyId="0" />
    	<Element colourId="text75"
             compName="hs_widget_background_p15_t1"
             text="Add"
             varietyId="0" />
        <Element compName="hs_widget_background_p6" skinId="qgn_home_bg_widget" varietyId="0"/>
    	<Element compName="hs_widget_background_g3"
             image="qgn_menu_cale.svg"
             loc_id="&lt;LC&gt;hs_widget_background_p6@v:0#r:1&lt;/LC&gt;"
             varietyId="0" />
    	<Element colourId="text75"
             compName="hs_widget_background_t3"
             loc_id="&lt;LC&gt;hs_widget_background_p6@v:0#r:1&lt;/LC&gt;"
             text="11:00 Proposals for Future D..."
             varietyId="0" />
    	<Element compName="hs_widget_background_g3"
             image="qgn_menu_cale.svg"
             loc_id="&lt;LC&gt;hs_widget_background_p6@v:0#r:2&lt;/LC&gt;"
             varietyId="0" />
    	<Element colourId="text75"
             compName="hs_widget_background_t3"
             loc_id="&lt;LC&gt;hs_widget_background_p6@v:0#r:2&lt;/LC&gt;"
             text="14:30 Lunch with Julian"
             varietyId="0" />
    	<Element compName="hs_widget_background_g3"
             image="qgn_menu_cale.svg"
             loc_id="&lt;LC&gt;hs_widget_background_p6@v:0#r:3&lt;/LC&gt;"
             varietyId="0" />
    	<Element colourId="text75"
             compName="hs_widget_background_t3"
             loc_id="&lt;LC&gt;hs_widget_background_p6@v:0#r:3&lt;/LC&gt;"
             text="18:00 Nightwish Concert"
             varietyId="0" />

    <Element compName="area_bottom_left_pane"
             display="640x360"
             skinId="qgn_fr_sctrl_sk_button"
             varietyId="0" />
    <Element compName="area_bottom_middle_pane"
             display="640x360"
             skinId="qgn_fr_sctrl_sk_button"
             varietyId="0" />
    <Element compName="area_bottom_right_pane"
             display="640x360"
             skinId="qgn_fr_sctrl_sk_button"
             varietyId="0" />
   	<Element colourId="text75"
             compName="hs_widget_clock_background_t1"
             text="10:30"
             varietyId="0" />
    <Element compName="hs_widget_clock_background_t2" skinId="text75" text="am" varietyId="0"/>

	<Element colourId="text15" compName="area_bottom_left_pane_t1" text="Options" varietyId="0"/>
   	<Element compName="area_bottom_middle_pane_g1" display="640x360"
			skinId="qgn_home_page_32"
			varietyId="0" /> 
             
	<Element colourId="text16" compName="area_bottom_right_pane_t1" text="Call" varietyId="0"/>

</preview_image>
</Preview>
