=== SymbianSource/oss.FCL.sftools.dev.ui/carbideui/com.nokia.tools.platform.core/src/dtds/preview.dtd
<?xml version='1.0' encoding='us-ascii'?>

<!--THIS FILE SHOULD NOT BE MODIFIED OR DELETED-->

<!--DTD for "preview design"-->

<!ELEMENT Preview (preview_image?)+ >
<!ATTLIST Preview
            name          	CDATA  		#IMPLIED	
            background    	CDATA  		#IMPLIED	
            MasterId	  	CDATA  		#IMPLIED
>


<!ELEMENT preview_image (Element?, reference? )+>


<!ATTLIST preview_image

	    name		CDATA	      	#REQUIRED
	    previewid		CDATA	      	#IMPLIED
	    preview		CDATA	      	#REQUIRED	
	    display		CDATA	      	#IMPLIED	
>

<!ELEMENT Element EMPTY>
<!ATTLIST Element 
	    compName		CDATA       	#REQUIRED
	    skinId		CDATA         	#IMPLIED
	    name		CDATA		#IMPLIED
	    optionId		CDATA         	#IMPLIED
	    varietyId		CDATA         	#REQUIRED		    	
	    level		CDATA         	#IMPLIED
            loc_id		CDATA         	#IMPLIED	            
       	    text		CDATA         	#IMPLIED			    
	    image		CDATA         	#IMPLIED
            is_mask		CDATA         	#IMPLIED	
            mask		CDATA         	#IMPLIED			                
            group		CDATA         	#IMPLIED	
            colourId		CDATA         	#IMPLIED            
            colour		CDATA         	#IMPLIED            
        	shape_link_id	CDATA         	#IMPLIED
            spl_mask_id		CDATA         	#IMPLIED
            scale_mode ( stretch | tile | tile_x | tile_y | aspect_ratio | scale_best | scale_fit | scale_down_fit ) #IMPLIED      			    
	    spl_mask_type	CDATA         	#IMPLIED
	    spl_mask_file	CDATA 	      	#IMPLIED	
	    opacity		CDATA   	#IMPLIED  
	    rotate		CDATA		#IMPLIED          
	    data		CDATA		#IMPLIED
	    text_full	CDATA		#IMPLIED
	    display		CDATA	      	#IMPLIED	
>
<!-- data is for link to additional metadata info system-->

<!ELEMENT reference EMPTY>
<!ATTLIST reference
	    screenName		CDATA       	#REQUIRED
>

=== SymbianSource/oss.FCL.sftools.dev.ui/carbideui/Symbian3/config/screens/360x640/Messaging.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Preview SYSTEM "preview.dtd">
<Preview>
	<preview_image display="portrait,square" name="Messaging" preview="true">
		
		<!-- Base screen 0 modified -->
		<Element compName="application_window"
             skinId="qsn_bg_screen"
             varietyId="0" />
    <Element compName="main_pane"
    		 display="360x640"
    		 skinId="qsn_bg_area_main"
    		 loc_id="&lt;LC&gt;application_window@v:0&lt;/LC&gt;"
    		 varietyId="0"/>
    <Element compName="status_pane_g2"
             skinId="qsn_bg_area_status"
             varietyId="0" />
    <Element compName="control_pane_g3"
             display="!360x640"
             skinId="qsn_bg_area_control"
             varietyId="0" />
    <Element compName="control_pane_g3"
             display="360x640"
             loc_id="&lt;LC&gt;area_bottom_pane@v:0&lt;/LC&gt;"
             skinId="qsn_bg_area_control"
             varietyId="0" />
    <Element colourId="icon2"
             compName="clock_nsta_pane_t2"
             text="12:28 PM"
             varietyId="0" />
    <!-- contents of status pane -->
    <Element compName="status_pane_g1"
             display="!360x640"
             skinId="qsn_bg_navipane_solid"
             varietyId="0" />
    <Element compName="status_pane_g1"
             display="360x640"
             loc_id="&lt;LC&gt;application_window@v:0&lt;/LC&gt;&lt;LC&gt;area_top_pane@v:16&lt;/LC&gt;"
             skinId="qsn_bg_navipane_solid"
             varietyId="0" />
    <Element compName="signal_pane_g1"
             skinId="qgn_indi_signal_strength"
             varietyId="0" />
    <Element colourId="icon5"
             compName="signal_pane_g2"
             image="qgn_prop_signal_icon.svg"
             varietyId="0" />
    
		<!--End Base screen 0 modified -->
		
		<Element compName="control_pane_g3" display="360x640" loc_id="&lt;LC&gt;area_bottom_pane@v:0&lt;/LC&gt;" skinId="qsn_bg_area_control" varietyId="0"/>

		<reference screenName="TouchPaneHorizontal0"/>
		
		<Element compName="status_pane_g1" display="360x640" loc_id="&lt;LC&gt;application_window@v:0&lt;/LC&gt;&lt;LC&gt;area_top_pane@v:16&lt;/LC&gt;" skinId="qsn_bg_navipane_solid" varietyId="0"/>	
		
		<!-- main area contents -->
		
		<Element compName="bg_list_pane_g1" display="360x640" loc_id="&lt;LC&gt;application_window@v:0&lt;/LC&gt;&lt;LC&gt;main_pane@v:8&lt;/LC&gt;&lt;LC&gt;bg_list_pane@v:0&lt;/LC&gt;" skinId="qsn_bg_column_AB" varietyId="2"/>	


		<Element colourId="icon3" compName="signal_pane_g1" image="qgn_indi_no_signal.svg" varietyId="0"/>
		<Element compName="battery_pane_g1" skinId="qgn_indi_battery_strength" varietyId="0"/>

		<Element colourId="icon6" compName="battery_pane_g2" image="qgn_prop_battery_icon.svg" varietyId="0"/>
		<Element colourId="text1" compName="title_pane_t1" text="Messaging" varietyId="5"/>

		<reference screenName="MainScrollBar0"/>

		<!--application contents-->
    
    <Element compName="list_highlight_pane_cp1" display="360x640" loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_double_large_graphic_pane@v:0&lt;/LC&gt;" skinId="S60_2_6%qsn_fr_list" varietyId="0"/>
    <Element compName="list_double_large_graphic_pane_g1" display="360x640" loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_double_large_graphic_pane@v:0&lt;/LC&gt;" skinId="qgn_prop_mce_write_sub" varietyId="0"/>
    <Element colourId="text10" compName="list_double_large_graphic_pane_t1" display="360x640" loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_double_large_graphic_pane@v:0&lt;/LC&gt;" text="New message" varietyId="0"/>
    
    <Element compName="list_double_large_graphic_pane_g1" display="360x640" loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_double_large_graphic_pane@#r:2#c:1&lt;/LC&gt;" skinId="qgn_prop_mce_inbox_sub" varietyId="0"/>
    <Element colourId="text6" compName="list_double_large_graphic_pane_t1" display="360x640" loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_double_large_graphic_pane@#r:2#c:1&lt;/LC&gt;" text="Inbox" varietyId="0"/>
    <Element colourId="text6" compName="list_double_large_graphic_pane_t2" display="360x640" loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_double_large_graphic_pane@#r:2#c:1&lt;/LC&gt;" text="No messages" varietyId="0"/>
    
    <Element compName="list_double_large_graphic_pane_g1" display="360x640" loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_double_large_graphic_pane@#r:3#c:1&lt;/LC&gt;" skinId="qgn_prop_mce_sent_sub" varietyId="0"/>
    <Element colourId="text6" compName="list_double_large_graphic_pane_t1" display="360x640" loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_double_large_graphic_pane@#r:3#c:1&lt;/LC&gt;" text="Sent items" varietyId="0"/>
    <Element colourId="text6" compName="list_double_large_graphic_pane_t2" display="360x640" loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_double_large_graphic_pane@#r:3#c:1&lt;/LC&gt;" text="No messages" varietyId="0"/>
    
    <Element compName="list_double_large_graphic_pane_g1" display="360x640" loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_double_large_graphic_pane@#r:4#c:1&lt;/LC&gt;" skinId="qgn_prop_mce_drafts_sub" varietyId="0"/>
    <Element colourId="text6" compName="list_double_large_graphic_pane_t1" display="360x640" loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_double_large_graphic_pane@#r:4#c:1&lt;/LC&gt;" text="Drafts" varietyId="0"/>
    <Element colourId="text6" compName="list_double_large_graphic_pane_t2" display="360x640" loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_double_large_graphic_pane@#r:4#c:1&lt;/LC&gt;" text="No messages" varietyId="0"/>
    
    <Element compName="list_double_large_graphic_pane_g1" display="360x640" loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_double_large_graphic_pane@#r:5#c:1&lt;/LC&gt;" skinId="qgn_prop_mce_outbox_sub" varietyId="0"/>
    <Element colourId="text6" compName="list_double_large_graphic_pane_t1" display="360x640" loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_double_large_graphic_pane@#r:5#c:1&lt;/LC&gt;" text="Outbox" varietyId="0"/>
    <Element colourId="text6" compName="list_double_large_graphic_pane_t2" display="360x640" loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_double_large_graphic_pane@#r:5#c:1&lt;/LC&gt;" text="No messages" varietyId="0"/>
	
	<Element compName="list_double_large_graphic_pane_g1" display="360x640" loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_double_large_graphic_pane@#r:6#c:1&lt;/LC&gt;" skinId="qgn_prop_mce_dr_sub" varietyId="0"/>
    <Element colourId="text6" compName="list_double_large_graphic_pane_t1" display="360x640" loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_double_large_graphic_pane@#r:6#c:1&lt;/LC&gt;" text="Delivery reports" varietyId="0"/>
    <Element colourId="text6" compName="list_double_large_graphic_pane_t2" display="360x640" loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_double_large_graphic_pane@#r:6#c:1&lt;/LC&gt;" text="Delivery info" varietyId="0"/>
	
	<Element compName="list_double_large_graphic_pane_g1" display="360x640" loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_double_large_graphic_pane@#r:7#c:1&lt;/LC&gt;" skinId="qgn_prop_mce_documents_sub" varietyId="0"/>
    <Element colourId="text6" compName="list_double_large_graphic_pane_t1" display="360x640" loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_double_large_graphic_pane@#r:7#c:1&lt;/LC&gt;" text="Documents" varietyId="0"/>
    <Element colourId="text6" compName="list_double_large_graphic_pane_t2" display="360x640" loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_double_large_graphic_pane@#r:7#c:1&lt;/LC&gt;" text="No messages" varietyId="0"/>
	
	
	

		<!-- control pane contents -->
		<reference screenName="BaseSoftkeys" />	
		<Element colourId="text13" compName="control_pane_t1" loc_id="&lt;LC&gt;area_bottom_pane@v:0&lt;/LC&gt;" text="Options" varietyId="4"/>
		
		<Element colourId="text14" compName="control_pane_t2" loc_id="&lt;LC&gt;area_bottom_pane@v:0&lt;/LC&gt;" text="Exit" varietyId="4"/>

	</preview_image>
	</Preview>

=== SymbianSource/oss.FCL.sftools.dev.ui/carbideui/Symbian3/config/screens/360x640/Note.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Preview SYSTEM "preview.dtd">
<Preview>
  <preview_image display="portrait,square"
                 name="Note"
                 preview="true">
                 
    <reference screenName="BaseScreen0" />
    <reference screenName="TouchPaneHorizontal0" />
    <reference screenName="MainScrollBar0" />
    <Element compName="bg_list_pane_g1"
             display="!360x640"
             skinId="qsn_bg_column_0"
             varietyId="0" />
    <Element compName="bg_list_pane_g1"
             display="360x640"
             loc_id="&lt;LC&gt;application_window@v:0&lt;/LC&gt;&lt;LC&gt;main_pane@v:18&lt;/LC&gt;&lt;LC&gt;bg_list_pane@v:0&lt;/LC&gt;"
             skinId="qsn_bg_column_0"
             varietyId="0" />
    <Element compName="bg_list_pane_g3"
             display="!360x640"
             skinId="qsn_bg_slice_list_0"
             varietyId="0" />
    <reference screenName="Profiles" />
    <!--<Element compName="screen_g1"
             image="screen_dimmer.svg"
             opacity="40"
             varietyId="0" />-->
    <Element compName="bg_popup_window_pane"
             display="!360x640"
             loc_id="&lt;LC&gt;main_pane@v:3#r:1&lt;/LC&gt;&lt;LC&gt;popup_query_data_window@v:0&lt;/LC&gt;"
             opacity="255"
             skinId="qsn_fr_popup"
             varietyId="0" />
    <Element colourId="text19"
             compName="popup_query_data_window_t2"
             display="!360x640"
             loc_id="&lt;LC&gt;main_pane@v:3#r:1&lt;/LC&gt;&lt;LC&gt;popup_query_data_window@v:0#r:1&lt;/LC&gt;"
             text="Activated profile:"
             varietyId="1" />
    <Element colourId="text19"
             compName="popup_query_data_window_t3"
             display="!360x640"
             loc_id="&lt;LC&gt;main_pane@v:3#r:1&lt;/LC&gt;&lt;LC&gt;popup_query_data_window@v:0#r:1&lt;/LC&gt;"
             text="General"
             varietyId="1" />
    <Element compName="popup_note_window_g1"
             display="!360x640"
             skinId="qgn_note_ok_anim"
             varietyId="0" /><!--
    <Element compName="bg_popup_window_pane"
             display="360x640"
             loc_id="&lt;LC&gt;main_pane@v:10&lt;/LC&gt;&lt;LC&gt;popup_query_data_window@v:0&lt;/LC&gt;&lt;LC&gt;popup_note_wait_window@v:0&lt;/LC&gt;"
             opacity="255"
             skinId="qsn_fr_popup"
             varietyId="0" />
             
    --><Element compName="bg_profile_popup_window_pane"
             display="360x640"
             opacity="255"
             skinId="qsn_fr_popup_preview"
             varietyId="0" />
    <Element colourId="text55"
             compName="profile_popup_window_text"
             display="360x640"
             text="Activated profile: General"
             varietyId="0" />         
             
                      
    <!--<Element colourId="text19"
             compName="popup_query_data_window_t2"
             display="360x640"
             loc_id="&lt;LC&gt;main_pane@v:10&lt;/LC&gt;&lt;LC&gt;popup_query_data_window@v:0&lt;/LC&gt;&lt;LC&gt;popup_note_wait_window@v:0&lt;/LC&gt;"
             text="Activated profile:"
             varietyId="1" />
    <Element colourId="text19"
             compName="popup_query_data_window_t3"
             display="360x640"
             loc_id="&lt;LC&gt;main_pane@v:10&lt;/LC&gt;&lt;LC&gt;popup_query_data_window@v:0&lt;/LC&gt;&lt;LC&gt;popup_note_wait_window@v:0&lt;/LC&gt;"
             text="General"
             varietyId="1" />
    <Element compName="popup_note_window_g1"
             display="360x640"
             loc_id="&lt;LC&gt;main_pane@v:10&lt;/LC&gt;&lt;LC&gt;popup_query_data_window@v:0&lt;/LC&gt;&lt;LC&gt;popup_note_wait_window@v:0&lt;/LC&gt;"
             skinId="qgn_note_ok_anim"
             varietyId="0" />
    --><!-- control pane contents -->
    <!--     <Element skinId="qsn_bg_slice_popup"
                        compName="bg_popup_window_pane_g10" varietyId="0"
                        loc_id="&lt;LC&gt;popup_menu_window@v:13&lt;/LC&gt;&lt;LC&gt;bg_popup_window_pane@v:0&lt;/LC&gt;" />
                <Element skinId="qsn_bg_area_control_popup"
                        compName="control_pane_g3" varietyId="0" /> -->
    <reference screenName="BaseSoftkeys" />
    <Element colourId="text13"
             compName="control_pane_t1"
             loc_id="&lt;LC&gt;area_bottom_pane@v:0&lt;/LC&gt;"
             text="Options"
             varietyId="4" />
    <Element colourId="text14"
             compName="control_pane_t2"
             loc_id="&lt;LC&gt;area_bottom_pane@v:0&lt;/LC&gt;"
             text="Back"
             varietyId="4" />

  </preview_image>
</Preview>

=== SymbianSource/oss.FCL.sftools.dev.ui/carbideui/Symbian3/config/screens/360x640/LargeList.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Preview SYSTEM "preview.dtd">
<Preview>
  <preview_image display="portrait,square"
                 name="Large List Icons"
                 preview="true">
    <reference screenName="BaseScreen0" />
    <reference screenName="TouchPaneHorizontal0" />
    <reference screenName="MainScrollBar3" />
    <!-- main area contents -->
    <Element compName="bg_list_pane_g1"
             display="!360x640"
             skinId="qsn_bg_column_AB"
             varietyId="2" />
    <Element compName="bg_list_pane_g1"
             display="360x640"
             loc_id="&lt;LC&gt;application_window@v:0&lt;/LC&gt;&lt;LC&gt;main_pane@v:18&lt;/LC&gt;&lt;LC&gt;bg_list_pane@v:0&lt;/LC&gt;"
             skinId="qsn_bg_column_AB"
             varietyId="2" />
    <!--   <Element skinId="qsn_bg_slice_list_AB"
                        compName="bg_list_pane_g3" varietyId="2" />
    <Element skinId="qgn_graf_line_primary_vertical_dashed"
                        compName="bg_list_pane_g4" varietyId="2" />
                <Element skinId="qgn_graf_line_primary_horizontal_dashed"
                        compName="bg_list_pane_g5" varietyId="2" /> -->
    <Element colourId="text1"
             compName="title_pane_t1"
             text="Large List"
             varietyId="5" />
    <!--            <reference screenName="ThreeTabPortrait" />
                <Element image="qgn_prop_file_music_tab4.svg" colourId="icon9"
                compName="tabs_4_1_passive_pane_g1" varietyId="0"
                loc_id="&lt;LC&gt;navi_pane@v:5&lt;/LC&gt;&lt;LC&gt;navi_navi_pane@v:0&lt;/LC&gt;&lt;LC&gt;tabs_3_passive_pane@v:2&lt;/LC&gt;" />
        <Element image="qgn_prop_file_video_tab4.svg" colourId="icon9"
                compName="tabs_4_1_passive_pane_g1" varietyId="0"
                loc_id="&lt;LC&gt;navi_pane@v:5&lt;/LC&gt;&lt;LC&gt;navi_navi_pane@v:0&lt;/LC&gt;&lt;LC&gt;tabs_3_passive_pane_cp@v:0&lt;/LC&gt;" />
                <Element image="qgn_prop_file_images_tab4.svg" colourId="icon8"
                compName="tabs_4_active_pane_g1" varietyId="0"
                loc_id="&lt;LC&gt;navi_pane@v:5&lt;/LC&gt;&lt;LC&gt;navi_navi_pane@v:0&lt;/LC&gt;&lt;LC&gt;tabs_3_active_pane@v:0&lt;/LC&gt;" /> -->
    <!--application content-->
    <Element compName="list_highlight_pane_cp1"
             display="!360x640"
             loc_id="&lt;LC&gt;list_double_large_graphic_pane@v:0#r:1&lt;/LC&gt;"
             skinId="S60_2_6%qsn_fr_list"
             varietyId="0" />
    <Element compName="list_double_large_graphic_pane_g1"
             display="!360x640"
             loc_id="&lt;LC&gt;list_double_large_graphic_pane@v:0#r:1&lt;/LC&gt;"
             skinId="qgn_prop_file_download"
             varietyId="0" />
    <Element colourId="text10"
             compName="list_double_large_graphic_pane_t1"
             display="!360x640"
             loc_id="&lt;LC&gt;list_double_large_graphic_pane@v:0#r:1&lt;/LC&gt;"
             text="Line 1"
             varietyId="0" />
    <Element colourId="text10"
             compName="list_double_large_graphic_pane_t2"
             display="!360x640"
             loc_id="&lt;LC&gt;list_double_large_graphic_pane@v:0#r:1&lt;/LC&gt;"
             text="3 folders, 35 files"
             varietyId="0" />
    <Element compName="list_double_large_graphic_pane_g1"
             display="!360x640"
             loc_id="&lt;LC&gt;list_double_large_graphic_pane@v:0#r:2&lt;/LC&gt;"
             skinId="qgn_prop_folder_large"
             varietyId="0" />
    <Element colourId="text6"
             compName="list_double_large_graphic_pane_t1"
             display="!360x640"
             loc_id="&lt;LC&gt;list_double_large_graphic_pane@v:0#r:2&lt;/LC&gt;"
             text="Line 2"
             varietyId="0" />
    <Element colourId="text6"
             compName="list_double_large_graphic_pane_t2"
             display="!360x640"
             loc_id="&lt;LC&gt;list_double_large_graphic_pane@v:0#r:2&lt;/LC&gt;"
             text="2 folders, 7 files"
             varietyId="0" />
    <Element compName="list_double_large_graphic_pane_g1"
             display="!360x640"
             loc_id="&lt;LC&gt;list_double_large_graphic_pane@v:0#r:3&lt;/LC&gt;"
             skinId="qgn_prop_group_large"
             varietyId="0" />
    <Element colourId="text6"
             compName="list_double_large_graphic_pane_t1"
             display="!360x640"
             loc_id="&lt;LC&gt;list_double_large_graphic_pane@v:0#r:3&lt;/LC&gt;"
             text="Line 3"
             varietyId="0" />
    <Element colourId="text6"
             compName="list_double_large_graphic_pane_t2"
             display="!360x640"
             loc_id="&lt;LC&gt;list_double_large_graphic_pane@v:0#r:3&lt;/LC&gt;"
             text="4 folders, 5 files"
             varietyId="0" />
    <Element compName="list_highlight_pane_cp1"
             display="360x640"
             loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_double_large_graphic_pane@v:0&lt;/LC&gt;"
             skinId="S60_2_6%qsn_fr_list"
             varietyId="0" />
    <Element compName="list_double_large_graphic_pane_g1"
             display="360x640"
             loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_double_large_graphic_pane@v:0&lt;/LC&gt;"
             skinId="qgn_prop_file_download"
             varietyId="0" />
    <Element colourId="text10"
             compName="list_double_large_graphic_pane_t1"
             display="360x640"
             loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_double_large_graphic_pane@v:0&lt;/LC&gt;"
             text="Line 1"
             varietyId="0" />
    <Element colourId="text10"
             compName="list_double_large_graphic_pane_t2"
             display="360x640"
             loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_double_large_graphic_pane@v:0&lt;/LC&gt;"
             text="3 folders, 35 files"
             varietyId="0" />
    <Element compName="list_double_large_graphic_pane_g1"
             display="360x640"
             loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_double_large_graphic_pane@#r:2#c:1&lt;/LC&gt;"
             skinId="qgn_prop_folder_large"
             varietyId="0" />
    <Element colourId="text6"
             compName="list_double_large_graphic_pane_t1"
             display="360x640"
             loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_double_large_graphic_pane@#r:2#c:1&lt;/LC&gt;"
             text="Line 2"
             varietyId="0" />
    <Element colourId="text6"
             compName="list_double_large_graphic_pane_t2"
             display="360x640"
             loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_double_large_graphic_pane@#r:2#c:1&lt;/LC&gt;"
             text="2 folders, 7 files"
             varietyId="0" />
    <Element compName="list_double_large_graphic_pane_g1"
             display="360x640"
             loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_double_large_graphic_pane@#r:3#c:1&lt;/LC&gt;"
             skinId="qgn_prop_group_large"
             varietyId="0" />
    <Element colourId="text6"
             compName="list_double_large_graphic_pane_t1"
             display="360x640"
             loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_double_large_graphic_pane@#r:3#c:1&lt;/LC&gt;"
             text="Line 3"
             varietyId="0" />
    <Element colourId="text6"
             compName="list_double_large_graphic_pane_t2"
             display="360x640"
             loc_id="&lt;LC&gt;main_pane@v:23&lt;/LC&gt;&lt;LC&gt;listscroll_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_gen_pane@v:0&lt;/LC&gt;&lt;LC&gt;list_double_large_graphic_pane@#r:3#c:1&lt;/LC&gt;"
             text="4 folders, 5 files"
             varietyId="0" />
    <!-- touch pane -->
    <!-- control pane contents -->
	<reference screenName="BaseSoftkeys" />	
    <Element colourId="text13"
             compName="control_pane_t1"
             loc_id="&lt;LC&gt;area_bottom_pane@v:0&lt;/LC&gt;"
             text="Options"
             varietyId="4" />
    <Element colourId="text56"
             compName="control_pane_t3"
             display="!360x640"
             text="Open"
             varietyId="3" />
    <Element colourId="text14"
             compName="control_pane_t2"
             loc_id="&lt;LC&gt;area_bottom_pane@v:0&lt;/LC&gt;"
             text="Back"
             varietyId="4" />
  </preview_image>
</Preview>
